### ISSUE TITLE
Publish ro-crate-inveniordm to conda-forge

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate-inveniordm#23]
Not blocked - all dependencies available on conda already.

**Comment by stain** [comment]
https://github.com/conda-forge/staged-recipes/pull/26848

**Comment by stain** [comment]
@elichad fixing bug in pull request to bypass CI failure.

**Comment by elichad** [comment]
https://anaconda.org/conda-forge/rocrate-inveniordm
